name: Nuget Package Publish

run-name: ${{ github.actor }} is running Nuget Publish

on:
  push:
    branches:
      - master

env:
  MASSIVE_TOKEN: ${{ secrets.MASSIVE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet clean Massive.Client.sln
          dotnet restore Massive.Client.sln
          dotnet build Massive.Client.sln

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet test Massive.Client.sln

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Package
        run: dotnet pack Massive.Client.sln

      - name: Publish Client
        run: |
          dotnet nuget push ./Massive.Client/bin/Release/*.nupkg  \
            -k $NUGET_AUTH_TOKEN \
            -s https://api.nuget.org/v3/index.json \
            --skip-duplicate
    
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}